class SpotExchange
  include Currency
  attr_accessor base: Currency
  attr_accessor quote: Currency

  def initialize:(base: Currency,quote: Currency) -> void
    @base = base
    @quote = quote
  end
end